import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Footer from '@/components/footer/footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Event Planner Application</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="wclassNameth=device-wclassNameth, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.body}>
        <div className={styles.header}>
          <div className={styles.container}>
            <div className={styles.branding}>
              <h1>Event Planner Application</h1>
            </div>
            <nav>
              <ul>
                <li className={styles.current}><a href="/">Home</a></li>
                <li><a href="events">Event</a></li>
                <li><a href="login">Login</a></li>
                <li><a href="signUp">SignUp</a></li>
              </ul>
            </nav>
          </div>
        </div>
      </div>
      <div className={styles.backimage}>
      <Image src="/images/showcase.jpg" 
      alt="My Image" width={1567} height={700}/>
      </div>

      <div className={styles.mainArea}>
      <div>
      <Image src="/images/card1.png" 
      alt="My Image" width={250} height={300}/>
                <h3>Virtual Events</h3>
                <p>See how Katie Sowers, Asst. Coach for the 49ers, uses Surface Pro 7 to put her plans into play.</p>
                <a href="">Learn More</a>
            </div>
            <div>
      <Image src="/images/sports.avif" 
      alt="My Image"width={250} height={300}/>
                <h3>Sports Events</h3>
                <p>See how Katie Sowers, Asst. Coach for the 49ers, uses Surface Pro 7 to put her plans into play.</p>
                <a href="">Learn More</a>
            </div>
            <div>
      <Image src="/images/card3.png" 
      alt="My Image" width={250} height={300}/>
                <h3>Auto Seats</h3>
                <p>See how Katie Sowers, Asst. Coach for the 49ers, uses Surface Pro 7 to put her plans into play.</p>
                <a href="">Learn More</a>
            </div>
            <div>
      <Image src="/images/tea.jfif" 
      alt="My Image" width={250} height={300}/>
                <h3>The International Tea Festival</h3>
                <p>See how Katie Sowers, Asst. Coach for the 49ers, uses Surface Pro 7 to put her plans into play.</p>
                <a href="">Learn More</a>
            </div>
      </div>
      <Footer/>
    </>
  )
}
